# Generated by Django 5.2.8 on 2025-11-14 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do motor', max_length=100)),
                ('potencia', models.DecimalField(decimal_places=2, help_text='Potência do motor em watts', max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
            ],
            options={
                'verbose_name': 'Motor',
                'verbose_name_plural': 'Motores',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Tipo do sensor (ex: temperatura, pressão)', max_length=50)),
                ('precisao', models.DecimalField(decimal_places=2, help_text='Precisão do sensor', max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
            },
        ),
        migrations.CreateModel(
            name='SensorMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.ForeignKey(help_text='Motor associado', on_delete=django.db.models.deletion.CASCADE, to='sensores.motor')),
                ('sensor', models.ForeignKey(help_text='Sensor associado', on_delete=django.db.models.deletion.CASCADE, to='sensores.sensor')),
            ],
            options={
                'verbose_name': 'Sensor do Motor',
                'verbose_name_plural': 'Sensores dos Motores',
            },
        ),
        migrations.CreateModel(
            name='DadosSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data e hora da coleta')),
                ('valor', models.FloatField(help_text='Valor coletado pelo sensor')),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('rpm', models.IntegerField(blank=True, null=True)),
                ('pressao', models.FloatField(blank=True, null=True)),
                ('fonte', models.CharField(default='MQTT', max_length=50)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('motor', models.ForeignKey(help_text='Motor relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='sensores.motor')),
                ('sensor', models.ForeignKey(help_text='Sensor que coletou o dado', on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='sensores.sensor')),
            ],
            options={
                'verbose_name': 'Dado do Sensor',
                'verbose_name_plural': 'Dados dos Sensores',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['-data_hora'], name='sensores_da_data_ho_dad67d_idx')],
            },
        ),
    ]
