# Generated by Django 5.2.8 on 2025-11-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadossensor',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadossensor',
            name='rpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadossensor',
            name='pressao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadossensor',
            name='fonte',
            field=models.CharField(default='MQTT', max_length=50),
        ),
        migrations.AddField(
            model_name='dadossensor',
            name='raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dadossensor',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data e hora da coleta'),
        ),
        migrations.AddIndex(
            model_name='dadossensor',
            index=models.Index(fields=['-data_hora'], name='sensores_da_data_ho_b7c89e_idx'),
        ),
    ]
