# Generated by Django 5.2.7 on 2025-11-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_update_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadossensor',
            options={'verbose_name': 'Dado do Sensor', 'verbose_name_plural': 'Dados dos Sensores'},
        ),
        migrations.AlterModelOptions(
            name='motor',
            options={'verbose_name': 'Motor', 'verbose_name_plural': 'Motores'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensores'},
        ),
    ]
